[tool.black]
line-length = 79
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
\.git |
\.hg |
\.mypy_cache |
\.tox |
\.venv |
_build |
buck-out |
build |
dist |
venv |
'''

[tool.isort]
profile='black'
multi_line_output=3
line_length=79
known_first_party='core,api,db,models'
filter_files=true
